language: php
dist: trusty
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install --dev --no-interaction
script:
  - mkdir -p report/logs
  - php vendor/bin/phpunit -c phpunit.xml

before_script:
  - composer require --dev php-coveralls/php-coveralls --no-interaction
  # need to enable xdebug in hhvm for code coverage
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v